name: EncryptFile_build_main

on:
  push:
    branches:
      - main
    paths:
      - 'Frends.Pgp.EncryptFile/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_main.yml@main
    with:
      workdir: Frends.Pgp.EncryptFile
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      